version: "2.1"

services:
  mongodb:
    image: mongo:4.1
    ports:
      - "27017:27017"
    networks:
      - todo_net

  todo:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - todo_net

networks:
  todo_net:
